@base_url = http://localhost:4000
@post_id = clvs0cwhv0000lsewcjs8xorv
@author_id = anyAuthorId

### Get all posts
GET {{base_url}}/get-posts

### Create a post
POST {{base_url}}/create-post
Content-Type: application/json

{
  "title": "New Post",
  "body": "This is a new post",
  "authorId": "{{author_id}}"
}

### Delete a post
POST {{base_url}}/delete-post
Content-Type: application/json

{
  "id": "{{post_id}}",
  "authorId": "{{author_id}}"
}

### Update a post
POST {{base_url}}/update-post
Content-Type: application/json

{
  "id": "{{post_id}}",
  "authorId": "{{author_id}}",
  "title": "Updated Post",
  "body": "This is an updated post",
  "published": "true"
}
